// src/components/Shop/shopData.js

export const PRODUCTS = [
  {
    id: "p1",
    name: "Round Neck T-Shirt",
    img: "/assets/img/product-1.png",
    rating: 4,
    price: 22,
    oldPrice: 27,
    colors: ["#c9d4ff", "#5fe6ff", "#9a7cff"],
    sizes: ["S", "M", "X", "XL"],
    badgeLeft: { text: "20%", color: "pink" },
    badgeRight: null,
  },
  {
    id: "p2",
    name: "Full Sleeve Shirt",
    img: "/assets/img/product-2.png",
    rating: 4,
    price: 10,
    oldPrice: 12,
    colors: ["#32e5ff", "#9f8bff"],
    sizes: ["S", "M"],
    badgeLeft: null,
    badgeRight: { text: "SALE", color: "green" },
  },
  {
    id: "p3",
    name: "Cute Baby Toy's",
    img: "/assets/img/product-3.png",
    rating: 4,
    price: 30,
    oldPrice: 40,
    colors: ["#b8d0ff", "#ff6a7a"],
    sizes: ["S", "M"],
    badgeLeft: null,
    badgeRight: null,
  },
  {
    id: "p4",
    name: "Jumbo Carry Bag",
    img: "/assets/img/product-4.png",
    rating: 4,
    price: 40,
    oldPrice: null,
    colors: ["#f3d06b"],
    sizes: [],
    badgeLeft: null,
    badgeRight: { text: "NEW", color: "blue" },
  },
  {
    id: "p5",
    name: "Designer Leather Purses",
    img: "/assets/img/product-5.png",
    rating: 4,
    price: 30,
    oldPrice: null,
    colors: ["#32e5ff", "#39f0a6", "#bdf06a"],
    sizes: ["S", "M"],
    badgeLeft: null,
    badgeRight: { text: "NEW", color: "blue" },
  },
  {
    id: "p6",
    name: "Canvas Cowboy Hat",
    img: "/assets/img/product-6.png",
    rating: 4,
    price: 10,
    oldPrice: 12,
    colors: ["#f2c879", "#bdf06a", "#58b7ff"],
    sizes: [],
    badgeLeft: null,
    badgeRight: { text: "NEW", color: "blue" },
  },
  {
    id: "p7",
    name: "Leather Belt for Men",
    img: "/assets/img/product-7.png",
    rating: 4,
    price: 10,
    oldPrice: null,
    colors: ["#c0c0c0", "#ffb199"],
    sizes: ["32"],
    badgeLeft: null,
    badgeRight: { text: "NEW", color: "blue" },
  },
  {
    id: "p8",
    name: "Digital Smart Watches",
    img: "/assets/img/product-8.png",
    rating: 4,
    price: 80,
    oldPrice: 100,
    colors: ["#e7e0db", "#ffd4cc", "#9fe6ff"],
    sizes: [],
    badgeLeft: { text: "20%", color: "pink" },
    badgeRight: { text: "NEW", color: "blue" },
  },

  // bạn có thể thêm tiếp các item để đủ 21 như template
];
